git clone git@bitbucket.org:gal16v8d/activemq.git
git clone git@bitbucket.org:gal16v8d/admin-server.git
git clone git@bitbucket.org:gal16v8d/applets.git
git clone git@bitbucket.org:gal16v8d/backup-util.git
git clone git@bitbucket.org:gal16v8d/bdconocimiento.git
git clone git@bitbucket.org:gal16v8d/biblioteca.git
git clone git@bitbucket.org:gal16v8d/bowlinggame.git
git clone git@bitbucket.org:gal16v8d/cloud-config.git
git clone git@bitbucket.org:gal16v8d/cloud-rest-client.git
git clone git@bitbucket.org:gal16v8d/conciliador.git
git clone git@bitbucket.org:gal16v8d/config-server.git
git clone git@bitbucket.org:gal16v8d/constant-util.git
git clone git@bitbucket.org:gal16v8d/cypher-util.git
git clone git@bitbucket.org:gal16v8d/db-util.git
git clone git@bitbucket.org:gal16v8d/demomongo.git
git clone git@bitbucket.org:gal16v8d/devdockervaadin.git
git clone git@bitbucket.org:gal16v8d/django-react.git
git clone git@bitbucket.org:gal16v8d/docker-config-util.git
git clone git@bitbucket.org:gal16v8d/dw1-svc.git
git clone git@bitbucket.org:gal16v8d/dw1-ui.git
git clone git@bitbucket.org:gal16v8d/dw2-hateoas-svc.git
git clone git@bitbucket.org:gal16v8d/dw2-svc.git
git clone git@bitbucket.org:gal16v8d/earthquake-svc.git
git clone git@bitbucket.org:gal16v8d/eureka-server.git
git clone git@bitbucket.org:gal16v8d/exception-util.git
git clone git@bitbucket.org:gal16v8d/file-util.git
git clone git@bitbucket.org:gal16v8d/fruit-app.git
git clone git@bitbucket.org:gal16v8d/fx-course-app.git
git clone git@bitbucket.org:gal16v8d/gateway-svc.git
git clone git@bitbucket.org:gal16v8d/gui-util.git
git clone git@bitbucket.org:gal16v8d/hackerrank.git
git clone git@bitbucket.org:gal16v8d/j2ee.git
git clone git@bitbucket.org:gal16v8d/jasper-util.git
git clone git@bitbucket.org:gal16v8d/jaxrs-client.git
git clone git@bitbucket.org:gal16v8d/jee-archetype.git
git clone git@bitbucket.org:gal16v8d/jeeservice.git
git clone git@bitbucket.org:gal16v8d/jenkins-job.git
git clone git@bitbucket.org:gal16v8d/key-manager-desktop.git
git clone git@bitbucket.org:gal16v8d/key-manager-react.git
git clone git@bitbucket.org:gal16v8d/key-manager-svc.git
git clone git@bitbucket.org:gal16v8d/knight-tour.git
git clone git@bitbucket.org:gal16v8d/mail-util.git
git clone git@bitbucket.org:gal16v8d/morse-app.git
git clone git@bitbucket.org:gal16v8d/parqueadero.git
git clone git@bitbucket.org:gal16v8d/pc-stock.git
git clone git@bitbucket.org:gal16v8d/pokemongo.git
git clone git@bitbucket.org:gal16v8d/print-util.git
git clone git@bitbucket.org:gal16v8d/property-util.git
git clone git@bitbucket.org:gal16v8d/qr-app.git
git clone git@bitbucket.org:gal16v8d/rabbitmq.git
git clone git@bitbucket.org:gal16v8d/redis.git
git clone git@bitbucket.org:gal16v8d/selenium-bot.git
git clone git@bitbucket.org:gal16v8d/serenity-bdd.git
git clone git@bitbucket.org:gal16v8d/sort.git
git clone git@bitbucket.org:gal16v8d/test-process.git
git clone git@bitbucket.org:gal16v8d/thorntail-demo.git
git clone git@bitbucket.org:gal16v8d/validator-util.git
git clone git@bitbucket.org:gal16v8d/videoplayer.git
git clone git@bitbucket.org:gal16v8d/youtube-bot.git
git clone git@bitbucket.org:gal16v8d/xls-util.git